server:
  port: 1641
spring:
  application:
    name: GeeMQ
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/aunt?serverTimezone=Asia/Shanghai
